# Generated by Django 5.2.8 on 2025-11-26 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
